### ISSUE TITLE
Applied OT did not reflect on final record

### ISSUE THREAD

**Issue by Annagwind** [vasavah/acenergykodanda#418] opened 2021-06-23 01:53 UTC
user: quezon

![image](https://user-images.githubusercontent.com/68258969/123022752-d6975180-d408-11eb-8a91-d31f559ca3e9.png)

Approved OT

![image](https://user-images.githubusercontent.com/68258969/123022811-ea42b800-d408-11eb-9301-3361b227b440.png)

**Comment by AnyaCee** [comment] 2021-06-24 03:43
RETURNED TICKET ISSUE:
Yes, you fixed the OT based on the screenshot we provided which is May 27, but if you were able to find the root cause, you would have also identified that there were also 2 other approved OTs:

![image007](https://user-images.githubusercontent.com/84363875/123199381-5d1f6200-d4e1-11eb-9106-030b56bbcb7e.jpg)
![image009](https://user-images.githubusercontent.com/84363875/123199118-d8344880-d4e0-11eb-9ea6-47451b077e0e.jpg)
![image008](https://user-images.githubusercontent.com/84363875/123199120-d8ccdf00-d4e0-11eb-8a79-376fe305c68b.jpg)

**Comment by Annagwind** [comment] 2021-06-26 11:32
Still an issue:
user: quezon

![image](https://user-images.githubusercontent.com/68258969/123511656-1b471500-d6b5-11eb-91cc-52358ffe2f64.png)


![image](https://user-images.githubusercontent.com/68258969/123511665-3580f300-d6b5-11eb-9d5b-949ac843148e.png)

**Comment by Annagwind** [comment] 2021-06-26 11:35
Still an issue:

user:quezon

![image](https://user-images.githubusercontent.com/68258969/123511716-90b2e580-d6b5-11eb-8479-1f9852270e47.png)


![image](https://user-images.githubusercontent.com/68258969/123511729-b0e2a480-d6b5-11eb-8fda-ad0d6859284d.png)

**Comment by Annagwind** [comment] 2021-06-26 11:43
user:ymalay

![image](https://user-images.githubusercontent.com/68258969/123511858-85ac8500-d6b6-11eb-86dc-edd71ddca779.png)

![image](https://user-images.githubusercontent.com/68258969/123511895-cf956b00-d6b6-11eb-8d17-3c2b5b4b3fef.png)

**Comment by Peterdelapena** [comment] 2021-07-05 09:13
Already tried lock/unlock of register and “recompute” button but it is still not reflecting correct OT values
![image](https://user-images.githubusercontent.com/84363701/124447656-2a644c00-ddb4-11eb-916d-df82d3aaf1c1.png)
![image](https://user-images.githubusercontent.com/84363701/124447693-32bc8700-ddb4-11eb-8a81-382699e07387.png)
![image](https://user-images.githubusercontent.com/84363701/124447735-3ea84900-ddb4-11eb-8901-560df8a4a5b5.png)

**Comment by AnyaCee** [comment] 2021-07-23 09:14
Validated as fixed, marked as closed

**Closed as completed** 2021-09-10 01:58 UTC
